# Specify the docker image to use (only used if using docker runners)
# See: http://doc.gitlab.com/ee/ci/docker/using_docker_images.html
image: ubuntu:18.10

# Define commands that run before each job's script
before_script:
  - apt-get update
  - apt-get install -y g++ gnuplot libgnuplot-iostream-dev cmake libarmadillo-dev nlohmann-json-dev libgtest-dev

stages:
  - compile
  - test
  - deploy

# Try to compile our sample hello world app
compile:
  stage: compile
  script:
  # Compile our app
    - mkdir cmake-build-debug
    - cd cmake-build-debug
    - cmake -DCMAKE_BUILD_TYPE=Debug -j8  ..
    - make -j8

test:
  stage: test
  script:
    - ./unit_tests

deploy:
  stage: deploy
  script:
    - cd ..
  # Save the compiled output from the above for downloading via GitLab and in Gitlab 8.6 to use in future build steps
  artifacts:
    paths:
    - cmake-build-debug/MCSM