image: docker:latest

services:
  - docker:dind

build:
  stage: build
  script:
    - docker build -t mcsm .
    - docker run --rm --user=gitlab-runner -v $PWD:/root/ --entrypoint bash mcsm /root/entrypoint.sh
  artifacts:
    paths:
      - MCSM_linux
      - unit_tests

test:
  stage: test
  dependencies:
    - build
  script:
    - chmod +x unit_tests
    - ls -la
    - pwd
    - /root/unit_tests --gtest_output="xml:report.xml"
    - ls -la
    - docker run --rm --user=gitlab-runner -v $PWD:/root/ --entrypoint /root/unit_tests ubuntu:18.10
